/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_LCD.h"
#include "D_BL_aliases.h"
#include "D_BL.h"
#include "GraphicLCDIntf.h"
#include "D_RST_aliases.h"
#include "D_RST.h"
#include "T_CS_aliases.h"
#include "T_CS.h"
#include "T_CLK_aliases.h"
#include "T_CLK.h"
#include "T_DIN_aliases.h"
#include "T_DIN.h"
#include "T_DO_aliases.h"
#include "T_DO.h"
#include "T_IRQ_aliases.h"
#include "T_IRQ.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "Clock_G.h"
#include "LED4_aliases.h"
#include "LED4.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

